BASE_URL = "https://jsonplaceholder.typicode.com/users"
SECRET_KEY_CLIENTE = "TESTE_DE_TOKEN_CLIENTE"
ALGORITHM = "HS256"
DATETIME_FORMAT = "yyyy-MM-dd HH:mm:ss.SSS Z"

ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdGUiLCJleHBpcmVkX2RhdGUiOiJ5eXl5LU1NLWRkIEhIOm1tOnNzLlNTUyBaIn0.IjptA6-THcjLWCs1x6kkXN-o0U0CnXU4IZc44NrK3FY"